#config.yaml

simulation:
  h: 0.05               # Sampling time [s]
  T_final: 1500         # Final simulation time [s]

load_condition:
  mp: 0.0               # Payload mass (front cabin) [kg]

ocean_current:
  V_c: 0.0 #0.3         # Ocean current speed [m/s] #0.2
  beta_c: 30.0          # Ocean current heading [rad]


waypoints: 
# Each column are a waypoint (x, y) in NED

# Waypoint lists for DP simulation

  x:      [0,  0, 15, 15, 0] 
  y:      [0, 15, 15,  0, 0] 
  angles: [0,  0,  0, -45]

# Waypoint list for path following simulation

  # Right turn then left turn
  #x: [0,  0, 40, 40] 
  #y: [0, 40, 40, 80] 

  #Zig zag
  #x: [5,  0,  5,  0,  5,  0]
  #y: [0, 10, 20, 30, 40, 50]

path_following:
  #Additional parameters for MPC DP mode
  R_switch: 0.4  # Radius for wpt switching in DP[m] #ideal: 0.25
  K_f: 0.3       # LOS observer gain

  #LOS and ALOS parameters
  Delta_h: 20    # Look-ahead distance
  gamma_h: 0.001 # ALOS adaptive gain

