#include <casadi/casadi.hpp>
#include "utilities.hpp"
using namespace casadi;

std::vector<double> controlAllocation(double Fx_des, double Fy_des, double Mz_des) {
    // Define symbolic decision variables
    MX F1 = MX::sym("F1");    // Thruster 1 force
    MX phi1 = MX::sym("phi1"); // Thruster 1 angle
    MX F2 = MX::sym("F2");    // Thruster 2 force
    MX phi2 = MX::sym("phi2"); // Thruster 2 angle

    // Combine decision variables
    MX vars = vertcat(F1, phi1, F2, phi2);

    // Thruster positions (example values)
    double L1 = 0.395;  // Distance of left thruster from centerline
    double L2 = 0.395;  // Distance of right thruster from centerline

    // Define the forces generated by the thrusters
    MX Fx = F1 * cos(phi1) + F2 * cos(phi2); // Surge force
    MX Fy = F1 * sin(phi1) + F2 * sin(phi2); // Sway force
    MX Mz = L1 * F1 * sin(phi1) - L2 * F2 * sin(phi2); // Yaw moment

    // Define the objective function (minimize squared error)
    MX objective = pow(Fx - Fx_des, 2) + pow(Fy - Fy_des, 2) + pow(Mz - Mz_des, 2);

    // Set up NLP problem dictionary
    MXDict nlp = {{"x", vars}, {"f", objective}}; 
    Dict opts;
    opts["ipopt.print_level"] = 0;  // Suppress IPOPT solver output
    opts["print_time"] = false;     // Disable CasADi timing output
    opts["ipopt.sb"] = "yes";       // Suppress IPOPT banner
    opts["ipopt.file_print_level"] = 0;  // Disable output to file
    opts["verbose"] = false;        // Disable verbose mode in CasADi

    opts["ipopt.max_iter"] = 50;
    Function solver = nlpsol("thr_alloc_solver", "ipopt", nlp, opts);

    // Initial guess
    DM x0 = DM::zeros(4,1);
    x0(0) = 50.0;  // Start with some positive thrust
    x0(1) = 0.0;   // Initial azimuth angle
    x0(2) = 50.0;
    x0(3) = 0.0;

    // Bounds
    DM lbx = DM::zeros(4,1);
    lbx(0) = -20.0;                    // Min thrust = 0
    lbx(1) = deg2rad(-90.0);          // Min azimuth angle
    lbx(2) = -20.0;
    lbx(3) = deg2rad(-90.0);

    DM ubx = DM::zeros(4,1);
    ubx(0) = 150.0;                   // Max thrust
    ubx(1) = deg2rad(90.0);           // Max azimuth angle
    ubx(2) = 150.0;
    ubx(3) = deg2rad(90.0);

    // Solve the NLP
    std::map<std::string, DM> args;
    args["x0"] = x0;
    args["lbx"] = lbx;
    args["ubx"] = ubx;

    std::map<std::string, DM> res = solver(args);    

    // Extract solution values
    DM sol = res.at("x");
    double F1_opt   = sol(0).scalar();
    double phi1_opt = sol(1).scalar();
    double F2_opt   = sol(2).scalar();
    double phi2_opt = sol(3).scalar();

    return {F1_opt, phi1_opt, F2_opt, phi2_opt};
}

